Coding-Coach/find-a-mentor

- src/mentors.json
> Adding myself as a mentor

- package.json
Updating the homepage with the new subdomain
> [FIX/homepage] Updating the home page

- README.md
Add Requirements in Readme
Advise using `yarn` to `npm` to favor consistency over the project and documentation
> Update Readme to add requirements 

- src/sematic-extra.css
> Fix: Mentor Card Buttons Position

- src/mentors.json
As requested in Slack this morning.
> Fix Slack link

- src/mentors.json
This PR adds me to the `mentors.json` file :)
> Add JavaScript Joe to mentors

- README.md
> Correcting path of mentors.json in README.md

- src/mentors.json
Hi,
Please let me know if I have missed anything.
Many thanks
Zhivko
> Add Zhivko Siderov as a mentor

- src/components/MentorsList/MentorList.css
- src/sematic-extra.css
> Fixed responsiveness for larger screens

- src/mentors.json
Meant to replace #51 because of over conflicts.
> Add Adebayo Opesanya as mentor - instead of #51

- src/mentors.json
> fix broken avatar not under https

- src/mentors.json
fyi: tests passed locally
Nice initiative! Happy to help out.
> Add Manuel Penaloza as mentor

- src/mentors.json
Sorry, have to update the description =X
> Add marina as mentor

- src/mentors.json
Would love to become a part of this great community!!!
> Add Molly Struve as Mentor

- src/mentors.json
> add Emma Wedekind as mentor

- src/mentors.json
Updated the mentors file with my details to be able to help.
- Updated the mentors file with my details.
> Add Etienne Marais as a mentor

- src/mentors.json
> Fix kenichi shibata Image

- src/mentors.json
Used the `yarn add-user` method to generate myself as a mentor, submitting PR to master for inclusion on the site.
Let me know if any changes are needed.
Thanks!
> add Shannon Duncan as mentor

- src/components/MentorsList/MentorList.css
> Fixed filters not showing properly on mobile view

- src/mentors.json
I would like to get added as a mentor please.
Thanks
> Add Chris DeMars as mentor

- src/mentors.json
Hello,
Here is my application to become a mentor!
Hope I can help some people learn web dev 🙌
Cheers!
> add Steven Yung as mentor

- src/mentors.json
hi there, a javascript, vuejs and python mentor here! 🖖 😄
> Add ruben valseca as mentor

- src/mentors.json
Updated the country code. Was listed incorrectly
> Add joran quinten as mentor

- src/mentors.json
> Add Stephan as Coding Coach Mentor

- src/mentors.json
> add Mahmoud Hesham as mentor

- src/mentors.json
Hello, 
Please accept my mentorship PR
> add Radi Mustafa as mentor

- README.md
- scripts/create-user.js
- src/__tests__/mentors.json-test.js
- src/channelProvider.js
PR for issue #74.
Additionally, have updated README.md and create-user to support adding GitHub account and personal website.
> Two channels added: github and personal website

- src/mentors.json
> Add Jacob Pretorius as mentor

- src/components/App/App.js
- src/components/Filter/Filter.css
- src/components/Filter/Filter.js
Addresses #148 
This adds a dynamic count of Mentors based on a users filter.
and filtered by `nodejs`
> Mentor Count

- src/mentors.json
> add Raffaele Pizzari as mentor

- src/mentors.json
Hi! This looks like exciting and a pleasure to be a part of. Could please review my request. Thanks.
> add Anit Shrestha Manandhar as mentor

- scripts/create-user.js
- src/mentors.json
When creating a new user, the list of countries is ordered by country code. This sorts it by the name of country, making it easier to find the country you're after.
> Sort country list in add user

- src/mentors.json
Oh gosh - it seems that prettier made a lot of changes here :/
Should I roll everything back? Let me know!
> Add alejandro nanez as mentor

- src/mentors.json
> Adding Jonny as a mentor

- src/mentors.json
Hi everyone!
Just adding myself as a mentor. Kudos on all the hard work! The project is looking great!
👋
> Add Patricio Cano as mentor

- src/mentors.json
> add Yi Sheng Siow as mentor

- src/components/Filter/Filter.js
- Added an aria-label to the toggle filters button
closes #178
> Added an aria-label for a button

- src/components/Card/Card.css
- src/components/Filter/Filter.css
- src/components/MentorsList/MentorList.css
I'm not sure if this breaks a11y changes...Not sure how best to test.
> Resolve issue 147 - Make filter position sticky

- src/mentors.json
> Add james best mentor

- src/mentors.json
Thanks for adding me to the list 💪
> add Jean-Vincent QUILICHINI as mentor

- src/mentors.json
Original PR had incorrect social handles.
> Add matt bidewell as mentor

- src/mentors.json
* Ran yarn add-user and fill the required information to become a Coding-Coach mentor.
> Add Raul Montero as mentor

- src/mentors.json
* Update avatar image in the mentors.json file for Raul Montero.
> Update image url for Raul Montero in mentors.json

- src/mentors.json
thanks for starting this platform!
> add Paul Hanaoka as mentor

- src/mentors.json
Fixed description after previous accidental PR.
> add Erik Ostrom as mentor

- scripts/add-mentor.js
Refer to review in #203 , 
Fix some typo in Add Mentors Script
> Typo Fix in Add Mentors Script

- src/mentors.json
> Add Wes Souza as mentor

- src/mentors.json
Adding myself as a mentor - excited to be here! 🎉
> Add Jacob Gillespie as mentor

- src/mentors.json
> add Benjamin Lannon as mentor

- src/mentors.json
@moshfeu thanks for pointing this out. Here is the fix.
> Fix Avatar URL

- src/mentors.json
Hi, I'd like to be added as a mentor.
Great idea!
> add Giacomo Rebonato as mentor

- src/__tests__/mentors.json-test.js
Added a build test to check for duplicated entries in mentors.json.
> Resolve Issue #207

- scripts/create-user.js
will produce this if we use **vue,react,JEST**
> Add synonyms check to add-user script

- package.json
- src/components/Card/Card.js
- yarn.lock
My first ever try with React and anything resembling modern JavaScript. I am open for any comments on how to improve this. I clearly see this can be done better, but lack the idea how.
This feature makes it harder for crawlers to scrape email addresses from the deployed web page. They are still scrappable from GitHub, but I'd like to address this in another PR.
> Obfuscate email addresses in UI

- src/mentors.json
I added myself as a new mentor 🌟👩‍💻
> a new mentor

- src/components/Switch/Switch.css
From what it is right now:
to:
> Proposal for toogle favorites transition

- src/mentors.json
> Add Matthew Jacobs as mentor

- src/mentors.json
Hi, I just updated my role and the avatar url.
> Update my role and avatar

- package.json
- scripts/create-user.js
- yarn.lock
This adds 2 things to make it easier for mentors to add themselves via the CLI.
1. Preemptive validation - adding validation rules to the prompts
2. Country typeahead - this allows mentors to skip having to scroll so much
> Add a few small enhancements to add-mentor CLI

- src/mentors.json
Let me know if you need me to do anything else! Thanks!
> Replace linkedin with slack and update email for Mentor Molly Struve

- package.json
- scripts/create-user.js
- yarn.lock
Will implement this:
Used this package:
https://github.com/sindresorhus/image-type
Is this correct can we improve?
> Added a validation to see if avatar link is an image

- src/mentors.json
> add Subramaniyan Annamalai as mentor - Fixed - waiting for merge

- src/mentors.json
> Remove Marina

- src/mentors.json
Really cool idea! Thanks for the opportunity to share what I've learned.
Looks as though the CLI did some reformatting on an entry adjacent to mine; content appears the same. See Line 4379
> Add Jason Wilson as mentor

- src/mentors.json
> Add Roman Glushko as Mentor

- src/mentors.json
I pointed to a picture that was 1.2Mb in size initially, sorry for that :)
> Updated profile photo with a smaller one

- src/mentors.json
Updates `mentors.json` with `spokenLanguages` key and adds default language of English to all mentors.
> Add Mentor Spoken Languages to Mentor Data

- src/mentors.json
> Add James George as a mentor

- src/__tests__/mentors.json-test.js
- src/components/App/App.js
- src/components/Header/Header.js
- src/components/Modal/ModalContent.js
- src/mentors.json
resolve #307
- Updated invalid website values in`mentors.json` to proper format
- Fail `yarn test` run when `mentors.json` is updated with non-conforming website
- Minor changes to existing code following the style applied automatically by IDE
> [issues/307] Website format fix

- .gitignore
- package.json
- scripts/pre-build.js
> Generate sitemap.xml in build

- src/mentors.json
> add Luis Merino as mentor

- src/components/App/App.css
- src/components/Filter/Filter.css
> make sidebar responsive so that bottom nav show correctly

- src/mentors.json
Opened again a PR because I closed the previous one and deleted the repository without merge :(
- Added Website tag
- Updated title
- Updated description
> Updated Ignacio's metadata. Not duplicated, see comment.

- src/mentors.json
Hello!
Please consider me, I'm especially interested in any interview questions or training people might want.
https://twitter.com/EmmaWedekind/status/1119631416051023877
> add Nick Larsen as mentor

- src/mentors.json
Fixed country code, updated title & description, fixed Twitter handle.
> Fix Brian Morrisons info.

- src/components/App/App.js
- src/components/Header/Header.js
- yarn.lock
https://github.com/Coding-Coach/coding-coach/issues/320
Removes Home in Navbar and changes the logo image from <a> to <img> no errors locally, successfully merged to master.
> Pull request for fix issue #320

- src/mentors.json
This is a PR to add me as a Mentor.
> add GaneshMani as mentor

- src/components/Card/Card.js
- src/helpers.js
I have updated the generateMentorId function as discussed and also created a separate module to keep all helper functions in one place, as we might keep on adding more & more helper functions in future and then we can reuse it in any place we want.
Closes #346
> Updated generateMentorId function

- src/mentors.json
Looking forward to joining the team! 👍
> add Ronan Connolly as mentor

- src/mentors.json
Hi! 🙋‍♂ Great project and I would be happy to join.
> add Fabian Gündel as mentor

- src/mentors.json
> add Omar Duarte as mentor

- src/mentors.json
Added new as a Mentor to coding coach repository
> Add Abhishek B. as Mentor

- src/mentors.json
- yarn.lock
Hola!  👋 
Does having this merged grant me write access on ephemeral branches?  I have a branch ready for a PR but get `Permission Denied` when attempting to push it.
> add Brent M Clark as mentor

- src/mentors.json
Hello, I would like to be a mentor.
> adds Joao Vanzuita as new mentor

- src/mentors.json
- Fix Ben's profile picture
- Update description
- Add GitHub profile
> Update Ben's info

- src/mentors.json
Glad to be part of the mentors 😄
> Add Ed Moore as mentor

- src/mentors.json
I speak a few more languages, Tamil & Telugu are added for now.
> Updated Praveen's profile.

- src/mentors.json
> Add Stan as mentor

- src/mentors.json
> Update João Antunes as mentor

- src/mentors.json
Thank you for creating this fantastic resource. I hope by becoming a mentor, I can help others 👍
> Add Suhail Patel as a mentor

- src/mentors.json
Unfortunately, I no longer have the time or mental capacity to be able to offer my time to help mentor junior developers.
Hopefully I'll be able to pick this back up some time in the future.
My apologies for any inconvenience this may cause!
> remove ben mallinson as mentor

- src/mentors.json
I added a new mentor as shown in the screenshot below:
> Add {Bolaji Ayodeji} as mentor

- src/mentors.json
Adds `Kyle Harrison` as a mentor. All details have been confirmed as correct, image is shown, and all links are working as expected.
> Add Kyle Harrison as mentor

- src/mentors.json
> Add aurore trunelle as mentor

- src/mentors.json
> add Maxence Poutord as mentor

- src/mentors.json
Hi, I've worked with Nodejs, Flask, Ruby-on-rails, Javascript, C++, Java, Python etc.
Would love to be a part of this initiative!
> Add Vaibhavi Singh as mentor

- src/mentors.json
Thanks for creating the amazing project!
> add Daniel Corner as mentor

- src/mentors.json
I love to share my knowledge. 👍
> Adding Dominik Hanke as a mentor

- src/mentors.json
I'm glad to be part of that great project
> Add Marcelo Ogeda as mentor

- src/components/App/App.css
- src/components/Filter/Filter.css
- src/components/Modal/ModalContent.js
> make sidebar responsive for max-height of 650px

- src/mentors.json
sorry but I'm currently not available anymore, maybe in the future I'll have more time again :)
thank you for your nice initiative 🙌
> remove Ruben Valseca

- src/mentors.json
Hi!
Sorry for the two `--force-with-lease` I've made, the build failed a couple of times and I would like to keep everything in only one commit :sweat_smile: 
Hope everything it's ok! And thank you for all your work! :bowing_man:
> add Ivan Gonzalez as mentor

- src/components/Filter/Filter.css
- src/components/MentorsList/MentorList.css
- src/components/MentorsList/MentorsList.js
- src/components/Modal/ModalContent.js
- src/components/Switch/Switch.css
resolve #433 .
Filters are now hidden on mobile if there are no results and the dropdown is closed.
> Filters are now hidden on mobile if there are no results

- src/mentors.json
Hi,
I am currently swamped between blogging and speaking engagements and given that I already have over 10 mentees that I am working with I can't take on any more at this time. Definitely will continue referring people here and likely will be joining again in the future! The experience has been incredible! 
Let me know if there is anything else you need me to do or if there is a better way other than deleting my information. Thanks!
Molly
> Remove Molly Struve From mentors.json

- src/mentors.json
I am currently unable to respond to requests for mentorship.
I think this service is great and hope it continues to thrive.
> Remove Matthew Jacobs as mentor

- src/mentors.json
@moshfeu Please checkout this PR.
> Add Praveen Kumar Saini as Mentor

- src/mentors.json
> add Caleb Meredith as mentor

- .travis.yml
- src/mentors.json
i was facing some issue in installing yarn on my machine, so couldn't run `yarn test`.  Please suggest if we have any workaround to test the schema.
> Add {Ravindra Sharma} as mentor

- src/mentors.json
@moshfeu kindly help me review this. Thank you
> talina shrotriya: rename tag: golang to go.

- src/mentors.json
Fixed Linkedin url and changed bio
> Add ilyas bakouch as mentor

- src/mentors.json
- Outdated avatar url
- Spoken languages
- Tags
- Description
- Channel facebook to website
> Update Mike Eling mentor

- src/mentors.json
- Add `javascript`
- Remove `graphql`
> add Samuel Osuh as mentor

- src/mentors.json
I have a few commitments in the coming months (about 4 -5 months) that would make it pretty difficult to me to be actively involved.
I do hope to return soon after.
> Request to remove as mentor

- src/mentors.json
> Add Joël as mentor

- src/mentors.json
Creating a pull request to update my profile information and social links. As those provided prior _(@JunoCodes)_ are no longer in use. Please reach out if you have any questions, issues, etc! 
Thanks.
> Update Justin Juno Mentor

- src/mentors.json
> Add Ivan Medina as mentor

- src/mentors.json
> Add ehren as mentor

- src/mentors.json
> add Vinod Shabadi as mentor

- src/mentors.json
Added Brian Christner as Mentor 
Signed-off-by: Brian Christner <brian.christner@gmail.com>
> Added Brian Christner as mentor

- src/components/Header/Header.js
- src/components/MemberArea/EditProfile.css
- src/components/MemberArea/EditProfile.js
- src/components/MobileNavigation/MobileNavigation.js
also fixes a bug that was showing the "Become a Mentor" legend on mobile navigation menu
>  fix #561: makes inputs on channel bigger

- src/mentors.json
Hi!
Just altering my personal details.
I've had a really fulfilling experience as a mentor so far.
> Update Andrew Healey details

- src/mentors.json
I recently started a new job and unfortunately I do not have capacity to take this on anymore. Please remove my entry 🙏
> Please remove my mentor entry?

- src/mentors.json
> add Ali Ghasemzadeh as mentor

- src/components/MemberArea/EditProfile.js
- src/components/Modal/Modal.js
Fixes the lint issues by running `yarn prettier:fix`
> Fix lint issues

- src/components/MemberArea/EditProfile.js
- src/components/MemberArea/model.js
> disable email field in edit profile

- src/components/MentorsList/MentorsList.js
> Refactor MentorsList component using hooks

- src/components/Header/Header.js
resolve #585 where the logo should be a link to https://codingcoach.io/
> Made logo in header into a link

- src/api/index.js
This PR are using the new API of pagination but request all the mentor a once until the all aspects of pagination will be ready.
It also `shuffle`s the list to get a diverse list of mentors.
> Use filters to align the new API + shuffle

- .gitpod.yml
- README.md
Hey there, slightly_smiling_face
this PR adds support for Gitpod, a free online tool that lets you automate your dev environment, eases the hurdles for contributions and generally working on GitHub projects. It allows anyone to get a ready-to-code dev environment for any branch, issue and pull request with a single click.
You can give it a try on my fork of the repo: https://gitpod.io/#https://github.com/nisarhassan12/find-a-mentor
It seems to work well! Please let me know if there is anything that can be improved. I would love to help :)
> Simplifies code contributions and automates the dev setup

- public/manifest.json
I set the theme and background colors to match the background color on the PWA logo to give it some form of uniformity.
> Updated background and theme colors

- package.json
- src/api/index.js
- src/index.js
- yarn.lock
- Install Sentry
- Configure Sentry
- Configure user scope for easier troubleshooting
close #611
> Add Sentry

- src/components/Card/Card.css
> mentors card UI update

- src/components/Navigation/Navigation.js
> add mentorship guidelines

- public/manifest.json
Should close #618 seeing it has been long for a long time now.
> Updated app name for PWA

- src/__tests__/App.test.js
- src/api/index.js
- src/components/App/App.js
- src/components/MemberArea/EditProfile.js
- src/components/MemberArea/MemberArea.js
- src/components/Navigation/Navigation.js
- src/context/userContext/UserContext.js
- src/index.js
Another implementation for user on context, this one has a better abstraction, but also is a bit more complicated, I think this should be the direction we should take
The `UserProvider` shouldn't be that high in the tree, I will down it once I start to work with the other parts of the context
> [FEAT] User-mentor moved to context #627 part

- src/components/App/App.js
- src/components/Filter/Filter.js
- src/components/MemberArea/EditProfile.js
- src/components/MemberArea/model.js
- src/context/filtersContext/FiltersContext.js
This is a WIP, is about 40% of the work, 
we need to move some things around and potentially clean a lot of code 🙌
> Moves filters from Filter.js file to context

- src/components/App/App.js
- src/components/AutoComplete/AutoComplete.js
> fix page navigation bug

- src/components/App/App.js
- src/components/AutoComplete/AutoComplete.js
- src/components/Card/Card.js
- src/components/Filter/Filter.js
- src/components/MentorsList/MentorsList.js
- src/context/filtersContext/FiltersContext.js
- src/ga.js
- src/index.js
- src/utils/permaLinkService.js
Sorry for the size of the PR is bigger than it should!
Important points: 
- Filters were moved to React Context, the architecture is based on this post: [How to use React Context effectively](https://kentcdodds.com/blog/how-to-use-react-context-effectively).
- `App.js` was refactored from class component to functional + hooks ↪️ 
- Favorites feature is broken 💔#652
- This PR closes #600 since the problematic code has been removed/replaced.
- More LoCs removed than added +286 −372 🎉
Feedback and manual testing is appreciated.
> Filters to context

- src/components/App/App.js
review and merge after #650
resolve #652
> Fix favorites

- src/api/index.js
- src/components/App/App.js
- src/components/Card/Card.js
- src/favoriteManager.js
- src/messages.js
> Store and Get the Favorites from the server

- src/api/index.js
- src/components/App/App.js
- src/components/Card/Card.css
- src/components/Card/Card.js
- src/components/Filter/Filter.css
- src/components/Filter/Filter.js
- src/components/MemberArea/MemberArea.js
- src/components/Switch/Switch.css
- src/components/Switch/Switch.js
- src/helpers/user.js
This current implementation is just for initial review. Please ignore the debug lines and the changes in Switch.js file. They are not fine-tuned yet.
resolve #663
> #663 Update mentor availability 

- package.json
- src/components/Me/Me.js
- src/index.js
- yarn.lock
resolves #669 
- adds react router dom to packages
- adds a main router for `/` root and `/me` routes
- adds a Me component that contains a router for sub routes `me/home`
- Me component checks if user is authenticated. If not, it redirects to `/`. -- This worked for me when i tested locally, but let me know if this simple check is enough for this ticket or if there is a better way of doing this. 
- i also added an example react router `Link` to 'me/home` in the Me component
> integrates react router, creates new component for protected sub routes

- src/api/index.js
- src/components/Card/Card.js
- src/components/MemberArea/EditProfile.js
- src/components/MemberArea/MemberArea.js
- src/components/MemberArea/model.js
- src/helpers/avatar.js
- yarn.lock
This PR allows the mentor upload and review their avatar instead of adding a link
resolve #673
> Mentor upload avatar

- src/api/index.js
- src/components/Card/Card.js
- src/components/MemberArea/EditProfile.js
- src/components/MemberArea/MemberArea.js
- src/components/MemberArea/model.js
- src/helpers/avatar.js
- yarn.lock
Instead of posting an external URL.
> Allow user to upload their avatar

- README.md
👆What it says on the tin.
The goal here is to aid in the overall flow from sentence to sentence; explaining why becoming a patron is a benefit to all.
> Wordsmithing the Support Us section

- package.json
- src/Me/components/Card/index.js
- src/__tests__/Card.test.js
- src/stories/card.stories.js
- yarn.lock
> Card Component

- src/components/MemberArea/tags.js
- RESTful API
- AJAX
- YAML
- JSON
- Webflow
> Added popular technologies

- src/Me/Modals/Modal.js
- src/stories/modal.stories.js
resolves #686 
Creates the Modal component for the Me area. 
Adds examples of Modal component to storybook: with title prop and with child content to demonstrate scroll behavior of content section.
> 686 feature modal

- src/Me/Me.js
- src/Me/Modals/EditMentorDetails.js
- src/Me/components/Button/Button.js
- src/Me/components/Button/Button.test.js
- src/Me/components/Button/__snapshots__/Button.test.js.snap
- src/Me/styles/global.js
- src/stories/button.stories.js
- src/utils/auth.js
- src/utils/overwriteProfileDefaults.js
> Allow mentors to delete their account

- src/Me/Modals/EditMentorDetails.js
- src/__tests__/App.test.js
- src/components/MemberArea/MemberArea.js
- src/config/experiments.js
This PR is the last piece of the new back office.
1. If adds a very basic experiments system so a feature can be closed directly from CI by changing a configuration or by setting a query param. The last part is useful for testing a feature before it released.
2. It changes the "edit your profile" link so instead of opening the modal, it redirects to the new back office. The "Become a mentor" link should remain the same - opens the modal.
> entry point + experiment

- src/Me/Profile/Profile.js
Fixing the title!
closes: #719
> Updating the title

- src/components/MemberArea/tags.js
https://twitter.com/moneymanolis/status/1300451441522376706?s=20 @crysfel
> Adding bitcoin tag

- src/Me/Navigation/Navbar.test.js
- src/Me/Routes/Home/Avatar/Avatar.js
- src/components/App/App.js
- src/favoriteManager.js
- smoke test for nav bar
- rename `toggle` to match use, 
- update deps arrays, 
- import 3rd party deps first
> Nav Bar test - remove eslint-disables for deps arrays

- src/components/Navigation/Navigation.js
> #171 add link to sessions calender

- src/Me/Header/Header.js
- src/Me/Header/Header.test.js
- src/Me/Me.js
Changed "Home" on mentorship request page to "Mentorships" .
> fixed mentorships request headline

- src/Me/AuthorizationRoute.tsx
- src/Me/Main.tsx
- src/Me/Me.tsx
- src/Me/MentorshipRequests/UsersList.tsx
- src/Me/Navigation/Navbar.test.tsx
- src/Me/Navigation/Navbar.tsx
- src/Me/Routes/Admin.tsx
- src/Me/components/Button/Button.tsx
- src/Me/components/Card/index.tsx
- src/api/admin.ts
- src/helpers/mentorship.ts
- src/types/models.d.ts
> feat: mentorships bird view

- src/CustomRoutes/AuthorizedRoute.tsx
- src/Me/Me.tsx
- src/Me/Modals/EditMentorDetails.tsx
- src/Me/Navigation/Navbar.tsx
- src/components/App/App.js
- src/components/Card/Card.js
- src/components/MemberArea/EditProfile.js
- src/components/MemberArea/MemberArea.js
- src/context/userContext/UserContext.tsx
- src/index.tsx
- src/utils/auth.js
fix: infinite loop when navigate to "me"
> improve: user context

- README.md
- src/Me/Modals/MentorshipRequestModals/AcceptModal.tsx
- src/Me/Modals/MentorshipRequestModals/MentorshipRequest.js
- src/Me/Modals/MentorshipRequestModals/style.ts
- src/Me/components/Textarea/Textarea.tsx
- src/components/MemberArea/EditProfile.js
- src/components/Navigation/Navigation.js
- src/config/constants.js
- src/config/constants.ts
- src/utils/auth.js
resolve #843
- All fields are now required and min length 30.
- Added some sentences to the description
Also resolve #844 - update the mentorship guidelines links
> imp(applying mentorship modal): encourage mentee for detailed request

- cypress/fixtures/mentorship-requests/get.json
- cypress/integration/me/mentorship-requests.spec.js
- src/Me/MentorshipRequests/ReqContent.js
> test: show mentee email upon approval

- src/api/index.ts
- src/context/authContext/AuthContext.tsx
- src/context/userContext/UserContext.tsx
- src/utils/auth.js
Root couse https://github.com/Coding-Coach/find-a-mentor/blob/13f5c14e3fd3418d94a30b5cf7d19652fdb341ac/src/context/authContext/AuthContext.tsx#L9 is async so https://github.com/Coding-Coach/find-a-mentor/blob/90a0277a01a2f0776a211db7dbbac374b541a33a/src/context/userContext/UserContext.tsx#L35 has been called before `renewSession` is completed, specifically https://github.com/Coding-Coach/find-a-mentor/blob/90a0277a01a2f0776a211db7dbbac374b541a33a/src/utils/auth.js#L61
> fix(login): require refresh after login

- pages/_app.tsx
This is for the "Fix user card styles" ticket
The reason is because the css var wasn't working (not imported in _app.js)
problem:
> fix: css vars not working

- next.config.js
- src/components/MentorsList/MentorsList.js
- src/context/mentorsContext/MentorsContext.js
- src/index.css
- Currently the `¯\_(ツ)_/¯ Wow, we can't believe it. We have nothing for you!` shows up before fetching the mentors is done.  This PR adds a `isLoading` variable to the context.
- Currently the `/me` menu icons appears without colors. This PR fixes it (by disabling `svgo` for now. More info https://github.com/gregberge/svgr/issues/680#issuecomment-1052442001)
Fixes https://github.com/orgs/Coding-Coach/projects/3#card-77678346
> fix: mentors loader & /me menu styles

- src/Me/Me.tsx
- src/Me/Navigation/Navbar.tsx
- src/components/layouts/App/ActionsHandler.tsx
- src/context/authContext/AuthContext.tsx
- src/context/userContext/UserContext.tsx
- src/utils/auth.js
Fixes https://github.com/orgs/Coding-Coach/projects/3#card-78304017
> fix: double redirection to auth0

- src/Me/Navigation/Navbar.tsx
A quick one to ensure routes come from the `routes` file.
> Use new routes for Me menu links

- pages/404.tsx
Completes: https://github.com/orgs/Coding-Coach/projects/3#card-77806666
This PR reintroduces our custom 404 page.
> Use custom 404

- src/Me/Main.tsx
- src/Me/Modals/MentorshipRequestModals/AcceptModal.tsx
- src/Me/Modals/MentorshipRequestModals/MentorshipRequest.js
- src/Me/Modals/MentorshipRequestModals/style.ts
- src/Me/Routes/Admin.tsx
- src/Me/components/Card/index.tsx
- src/Me/components/Textarea/Textarea.tsx
- src/PageNotFound.tsx
fix svg files from cra format as image to a component. Also fixed some styles around them and modals
> fix: svgs and styles

- next-env.d.ts
- src/api/index.ts
- src/context/mentorsContext/MentorsContext.js
- tsconfig.json
It's just not working because of a bad argument list
> fix: add to favorites

- src/components/Content/Content.css
> fix: mentor apply modal cut

- src/components/MemberArea/PendingApplications.js
- src/components/Modal/Modal.css
> fix: horizontal scroll in modals

- src/Me/Modals/model.tsx
- src/components/MemberArea/model.js
1. Fixed min length to be 3
2. Add the info to the help text accordingly
> Fix the "Title" field obscurity

- src/api/index.ts
Getting error
```
_app-a368b32968dfe9e3.js:1 
Uncaught (in promise) TypeError: r.configureScope is not a function
```
> fix: user avatar isn't clickable

- netlify/functions-src/functions/data/utils.ts
- netlify/functions-src/functions/email/emails.ts
- netlify/functions-src/functions/email/sendgrid.ts
- netlify/functions-src/functions/modules/mentors/applications/post.ts
- netlify/functions-src/functions/modules/mentors/applications/put.ts
- netlify/functions-src/functions/modules/mentorships/apply.ts
- netlify/functions-src/functions/modules/mentorships/requests.ts
- netlify/functions-src/functions/modules/users/verify.ts
Fix issue where async code in Netlify function wasn’t executed due to early termination after handler completion
> fix(emails): emails were not sent

- netlify/functions-src/mongo-scripts/get-mentors.mongodb.js
- src/components/MemberArea/model.js
[Original issue](https://coding-coach.slack.com/archives/CCR78Q1LY/p1747072256398259?thread_ts=1746992150.626819&cid=CCR78Q1LY)
> fix(become-mentor): accept avatars from google
