src/components/SocialLinks/SocialLinks.js
The homepage Slack invite link was an older invalid one.
This commit replaces that link with the current valid one.
The Slack link in the README was already updated.
Fixes [#137]
=> Update Slack invite link on homepage

README.md, package.json, scripts/create-user.js, src/__tests__/mentors.json-test.js, src/mentors.json, yarn.lock
The search for tags compares the tags directly. Since the search always uses downcased tags it fails for tags which have uppercase characters in them.
This PR adds a restriction to the tests to ensure that the tags are all lowercase. It does this by adding a `pattern` criteria to the tags JSON schema. It also improves the output for the schema test to actually display the violating value and the mentor which makes finding offending values a lot more easy.
=> Ensure tags are lowercase with the tests

src/components/Card/Card.js
This PR simply ensures that the channel icons are always listed in the same order (alphabetically). 
Will resolve #219
=> Ensures channel icons are always listed in alphabetical order.

public/index.html
Added a meta description so that we pass the seo audit to 100, the current one online:
Normally this should be a call to action, just need to decide on the text we use 😃 
I made a quick one, but needs improvements, this should be between 130-160 letters
Some examples at the end of this article:
https://www.2dogsdesign.com/what-is-meta-description/
=> Add meta description to improve seo audit to 100%

scripts/create-user.js
Fixing method _hasLessThanOneOrMoreThanFiveTags_
If you just press Enter without typing a tag the value will be ' ' and when you split it will produce [' '] therefore if no tag is sent count will be 1 passing this validation with no tags
if we change to this it solves the empty problem 😄
=> Fix tag count validation in add-user script

src/mentors.json
The Northern Ireland flag isn't appearing so I changed it to render the flag for "Ireland."
=> Fixing emoji flag for "Northern Ireland"

src/components/Card/Card.js
=> Add key to Obfuscate to remove warning when you run tests

public/index.html
This is missing as it looks very bad.
@emmawedekind and @moshfeu see how it looks ("Full Stack Developer, LAMP / MERN Stack specialising in UX & Front End Tech." part):
If we have added the right fonts by including Lato Italic and then using it, it looks like this:
Hence the PR. 😅
=> Added italic version of Lato.

scripts/create-user.js, src/__tests__/mentors.json-test.js, src/checkSynonymsTags.js
Put the synonyms check for tags in one place only, as request by @moshfeu 
Can it be improved?
=> Centralize Synonyms Check for Tags

src/components/Card/Card.css, src/components/Card/Card.js
👋 This PR aims to solve issue #294. You can see the updated styling of the cards here: 
There were a couple of issues that need addressed:
1. there doesn't seem to be enough space for the full country name. It results in weird formatting of countries with a name longer than one word and there was an issue with the avatar being pushed over by the text, but that's easily resolved: 
2. If a mentor has plenty of information, the elements move downwards, meaning that the card next to it has a different "layout" of elements: 
I'd like to resolve this ☝🏻using CSS grid to keep the elements in a set space. But would like to do this in a separate PR.
=> Task/i 294/update card styles

src/components/MentorsList/MentorsList.js
resolves #329 
The bug of the window jumping back to the top was only occurring when on a larger screen width with 5 or more mentor card items per row. So i think it has something to do with how the mentors list is being rendered/re-rendered in the infinite scroll component based on pages. When the `itemsInPage` value is greater than the total of items in 2 rows, it seems to solve the bug. I've tried stepping through code with a debugger to figure out why this fixes it, but still not sure. 
If anyone else wants to look into it and understands why, and/or propose an alternate solution, let me know!
=> increase items per page for infinite scroll list

src/__tests__/mentors.json-test.js
As suggested in https://github.com/Coding-Coach/find-a-mentor/issues/307#issuecomment-483548210 website format validation can be moved to global schema check--
To-do:
instead of: 
because
https://github.com/Coding-Coach/find-a-mentor/blob/e30f89c08dbd8a0a9076330438601af1ae785cb3/src/__tests__/mentors.json-test.js#L176 replaces `channels[0]` with `channels.0`.
Will fix shortly c:
=> [issues/307] Website format validation as part of ajv schema check

src/components/App/App.js, src/components/AutoComplete/AutoComplete.js, src/components/Card/Card.css, src/components/Card/Card.js, src/components/Filter/Filter.js, src/components/MentorsList/MentorsList.js
I took a shot at implementing the feature to click the country icons in mentor cards.
I mainly took inspiration from the implementation of language tags. Happy to hear what you think.
It might be worth in the future to add hover, focus states and other accessibility features throughout the code base. 
Closes #370
=> feat: clickable location tags to filter mentor list

src/mentors.json
My other URL was 403 Forbidden.
This should fix it.
=> add new photo URL

README.md, scripts/add-mentor.js
First time I had run ```yarn run add-user``` it started an infinite loop waiting for the GitHub repository password (password request didn't display).
Calling git pull synchronously allowed me to enter the password and "git pull" my fork:
```js
await execa.sync('git', ['pull']);
```
So I tried it on Windows, and I'm not able to run the same command or similar without some workarounds and OS verification.
To avoid these workarounds and OS verification that will increase the script complexity, I would like to suggest to remove the `git pull` call from the add-user script.
=> removes "git pull" step from user-add script

README.md, package.json, scripts/create-user.js, scripts/pre-build.js, src/__tests__/mentors.json-test.js, src/components/App/App.js, src/components/Filter/Filter.js, src/listsGenerator.js, src/titleGenerator.js
resolves #293 
Adds language autocomplete to filter sidebar, updates mentor schema and manual instructions, and adds cli question with a searchable checkbox. 
Should languages be added to the required fields in the mentor schema? I left it out and used the logic in the `filterMentors` function in `app.js` for backwards compatibility. English is selected/added as a default going forward. Alternatively, the current `mentors.json` can be updated so each mentor has it as a default and the extra check in filter mentors can be removed, but i'm unsure how to do this.
=> 293 language autocomplete

src/components/AutoComplete/AutoComplete.js
As shown below, the autocomplete functionality of the browser is really disruptive to filtering, one case (Language) it takes very little for the autocomplete to completely obscure the underlying dropdown.  
It did not seem like the intention was to allow browser-based autocompletion in this filtering, so I've cut a PR to turn it off.
=> prevent autocomplete

src/components/App/App.css
ToDo: We should make it scrollable in smaller height devices so that the rest is viewable. I just fixed the bad part.
Currently it looks like:
Proposed CSS will make it:
=> Made the left sidebar responsive.

.travis.yml, package.json
It looks like the build process is not replacing the `%PUBLIC_URL%` hence the meta tags are not created with absolute URLs.
%PUBLIC_URL% in `public/index.html` will get replaced during build
only if the NODE_ENV is set to production.
Setting the `PUBLIC_URL` will ensure that all meta tags are created
correctly for Social Media Sharing and previews.
resolve #428
=> Fix #428: Added PUBLIC_URL and NODE_ENV to be injected during build

cypress/support/commands.js
What this PR does:
* Now `name` param passed to the `filterByName` method is used
Resolve #478
=> Issue #478 Unused `name` param in Cypress Support Commands

.gitignore, cypress/integration/mentors.js, cypress/support/commands.js, src/components/AutoComplete/AutoComplete.css, src/components/AutoComplete/AutoComplete.js, src/components/Filter/Filter.js, src/components/FilterClear/FilterClear.css, src/components/FilterClear/FilterClear.js
What this PR does:
Resolve: #498 
Added a clear button/icon at the right of the autocomplete filter, when it is clicked, the autocomplete input is cleared.
This "clear" button is optional, because we can reuse the autocomplete in another places where we don't need to clear the value by default.
How to test
* Just add some filters. It should looks like this picture:
TODO:
[ ] Implement tests
=> Issue 498 clear btn on autocomplete filters

src/components/MemberArea/model.js
It reads Up tp 5 on the site right now, this commit fixes that.
=> Typo fix for tags help text

src/components/MemberArea/model.js
The issue was that members could add invalid syntax to the linkedin
input field that would cause the link to be invalid. This PR adds
a REGEX pattern that does input validation.
For the input to be valid it must contain the following according
to Linkedin.
* 3 - 100 letters or numbers (capital letters are allowed)
* No spaces, symbols or special characters (except hyphen which is allowed)
fixes #592
=> Fix/Add input validation to the Linkedin channel field

src/components/MemberArea/EditProfile.css, src/components/MemberArea/EditProfile.js, src/components/MemberArea/model.js
This pr validates the input field for facebook, github and twitter. It fixes the issue #629. Here is a screenshot of the updated view with the help text
=> Fix #629: Add validations for facebook, Github and Twitter username

src/context/filtersContext/FiltersContext.js
The problem was after the execution of first filterReducer action, all the state params were getting assigned with undefined value except the one for which the action was invoked. This was leading to problematic behaviour. 
This fix makes sure that when one of the state params is getting changed, others are kept intact.
resolve #646
=> #646: Filers fields are visible while app is loading

src/components/Card/Card.css, src/components/MemberArea/EditProfile.css, src/components/MemberArea/EditProfile.js, src/components/MemberArea/model.js, src/helpers/user.js, src/index.css, src/utils/overwriteProfileDefaults.js
* Created a function that will prevent populating the avatar and name
values when editing a profile if they match the default auth0 values
* Improved the validation function for names to require a space.
Fixes: https://github.com/Coding-Coach/find-a-mentor/issues/639
=> Overwrite default auth0 name and avatar (Issue #639)

README.md
Quick fix to the Readme to change line item "Reach them out" to "Reach out to them" in the mentee guidelines.
=> Fix typo in Mentee guidelines

src/Me/Me.js, src/Me/styles/global.js, src/context/modalContext/ModalContext.jsx
Scrollbars come from body and modal container. 
Set body `overflow: hidden` when a modal is open.
=> #686 - Prevent 2 scrollbars when modal is open

cypress/integration/login.spec.js, cypress/integration/mentors.js, package.json, yarn.lock
No card for this one, but I said I would do it in Slack.  So, here it is!
The latest version of Cypress has arrived.  Although the use of `cy.server()` and `cy.route()` remain intact, they are considered deprecated.  To that end, I updated the few calls we had to that deprecated API and converted them to the new `cy.intercept()` syntax.
=> Upgrade Cypress version to 6.2.0

src/components/MemberArea/MemberArea.js, src/context/userContext/UserContext.js
Currently when "newBackoffice" experiment is open, "become mentor" redirect to the new backoffice instead of showing the modal (the new backoffice is not ready for becoming mentor process.
=> fix: keep "become mentor" modal

src/Me/Modals/EditMentorDetails.js, src/Me/Modals/model.js
In some devices the Slack channel label breaks into 2 lines and expand the view port
=> fix(mentor-details): adjust slack

package.json
Troubleshooting with Bo and we found that `prop-types` is not currently a dependency, but should be as it is imported explicitly - `Button.js`, `List.js`, `ListItem.js`, `Select.js`  
This hasn't broken builds in past, because `prop-types` is currently included via peer deps
=> add missing dep `prop-types` to package.json

src/Me/Modals/MentorshipReqModals/MentorshipRequest.js, src/Me/Modals/Modal.js, src/api/index.js
fix #778 
Currently, the client doesn't know how to handle server validation errors payload. So far, the server returns only string errors.
The server validation errors' payload is different and contains an array of errors. This why the client didn't show anything and just closed the modal.
This PRs aims to handle them and show the validation error in a red toast, the same way it does with string base errors.
Although it doesn't solve directly the client validation of the 400 characters but I believe it's a better approach since we might change the limit from time to time.
=> fix(request-modal): toast server validation errors

src/Me/Modals/EditMentorDetails.tsx, src/Me/Modals/MentorshipReqModals/AcceptModal.tsx, src/Me/Modals/MentorshipReqModals/DeclineModal.tsx, src/Me/Modals/MentorshipReqModals/MentorshipRequest.js, src/Me/Modals/MentorshipReqModals/stories/AcceptModal.stories.tsx, src/Me/Modals/MentorshipReqModals/stories/DeclineModal.stories.tsx, src/Me/Modals/MentorshipReqModals/stories/MentorshipRequest.stories.tsx, src/Me/Modals/Modal.tsx, src/Me/Profile/Profile.tsx, src/context/modalContext/ModalContext.tsx
- Move `closeModal` to modal context to avoid the (types) need to pass from the caller.
- Improve UI - Add an overlay (half opacity + blur) to let the user focus on the modal.
=> improve(modal): move closeModal to context + ui and animation

src/Me/Me.tsx, src/utils/auth.js
Card: https://github.com/orgs/Coding-Coach/projects/3#card-78126400
This PR forces authentication on all `/me` routes using a client-side call to `auth.login()` if there's no current user.
=> Force authentication for "me" routes

src/components/UserProfile/UserProfile.tsx, src/utils/routes.ts
Completes: https://github.com/orgs/Coding-Coach/projects/3#card-78129859
Leveraging the new `routes` file, we can now selectively tack on the search params to our URLs with centralized logic.
=> Persist Filters on Navigation

src/components/UserProfile/UserProfile.tsx
Fixes: https://github.com/orgs/Coding-Coach/projects/3#card-78129813
Since the app takes a brief moment to load, it was sending `undefined` as the `userid` to `getUser`.  Everything would eventually snap into place and work fine, but the toast for the bad request would still show, which was the correct thing to do.  Now, we don't fire that API call until we have an id.
=> Prevent User Not Found toast on user profile page load

package.json, src/Me/Me.tsx, src/PageNotFound.tsx, src/components/Navigation/Navigation.js, src/components/UserProfile/UserProfile.tsx, yarn.lock
Closes: https://github.com/orgs/Coding-Coach/projects/3#card-78303000
React Helmet is great, but the native `next/head` is better for Nextjs applications.  So, we switch.
=> Remove react-helmet in favor of next/head

src/Me/MentorshipRequests/UsersList.tsx, src/Me/components/RichList/ReachItemTypes.d.ts, src/Me/components/RichList/RichItem.tsx, src/components/UserProfile/UserProfile.tsx, src/context/apiContext/ApiContext.tsx, src/hooks/useRoutes.ts
It's a very major bug!
Mentees can't get their mentor details since we fetch the mentor details in the server (for ssr) but the call is anonymous so the channels are always an empty array.
The patch for now is to take the channels from the mentor list we fetch anyway (and it's not anonymous).
The perfect ultimate solution is to make the ssr call not anonymous (by moving the auth details from the localStorage to cookie - see #921) so the API wiil return the channels with the user response.
=> fix: mentor's channel are not available

src/components/Card/Card.tsx
When I go to my mentor page and (s)he is not available I can't get their contact details.
Why? Because we first check if the mentor is available. If not we show the not available line.
The solution is to check also if (s)he is my mentor.
=> fix: mentors channels are not available when they are not available

src/api/index.ts
Fixes #929
A simpler fix would have been to reverse the API return order, but that seems to be in another repo.
=> Reverse the order listing to be most-recent first

src/helpers/time.ts
For users that joined over a year ago. The profile card in find-a-mentor returns months instead of years. For example, I joined exactly one year ago but the profile card shows 1months ago.
=> Bug Fix - fixed date on profile card showing months instead of year.

src/components/Card/Card.tsx
Move 'CardHeader\CardFooter' out of the Card component for saving unnecessary computing and renders
Before change (look at Mentor 7 and 8 on clicking on like button):
https://github.com/Coding-Coach/find-a-mentor/assets/87114926/6578345c-eade-47c1-8f9c-f11d328c63cd
After change:
https://github.com/Coding-Coach/find-a-mentor/assets/87114926/061572e8-30cb-481b-8122-8e574e2f76da
For deeply understanding the problem, you can refer to [calling function component](https://medium.com/missive-app/45-faster-react-functional-components-now-3509a668e69f) and [why don't call function component](https://kentcdodds.com/blog/dont-call-a-react-function-component)
=> Fix unnecessary Avatar renders which cause extra unnecessary alt text

src/Me/Modals/MentorshipRequestModals/MentorshipRequest.js
The bug is that once a field’s validation failed it didn’t became valid even when the content has extended **and** the server returns an error
=> fix(mentorship-request): validation keeps show up when it's resolved on server error
